name: AnneMiller
favicon: null
layout_spectrum: 0.5458551216870546
typography_spectrum: 0.5019140425138175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5051731632556766
  lightness: 0.16122695640660822
  saturation: 0.1936936816200614
  rhythmicContrast: 0.15611729794181883
purpose: []
